### PR TITLE
Fix MacOS PrusaSlicer bug

### LINKED ISSUE #11: Cant use script as post-processing script but console works
Hi. I tried to use the script, both in prusaslicer and via console.
In prusaslicer I got this error: 
`Post-processing script /usr/local/Cellar/python@3.10/3.10.10_1/bin/python3.10 /Users/andrearossetti/Library/Application)
Support/PrusaSlicer-alpha/prusa_slicer_post_processing_script.py on file /var/folders/7q/qzjmm0d121_gtxOycd6vryr0000gn/T/.40741.gcode.pp failed.
Error code: 1
Output:
Traceback (most recent call last):
File "/Users/andrearossetti/Library/Application Support/PrusaSlicer-alpha/prusa_slicer_post_processing_script.py", line 1158, in
<module>
main(gCodeFileStream,path2GCode)
File "/Users/andrearossetti/Library/Application Support/PrusaSlicer-alpha/prusa_slicer_post_processing _script.py", line 374, in
main
input("Push enter to close this window")
EOFError: EOF when reading a line`

And via console I can finish the script but it doesn't change anything. This is what I got from console:
`/usr/local/Cellar/python@3.10/3.10.10_1/bin/python3.10 /Users/andrearossetti/Library/Application\ Support/PrusaSlicer-alpha/prusa_slicer_post_processing_script.py /Users/andrearossetti/Downloads/Unito_0.2mm_PETG_MK3S_1h15m.gcode
/Users/andrearossetti/Library/Application Support/PrusaSlicer-alpha/prusa_slicer_post_processing_script.py:1070: Travel Moves may cross the outline and therefore cause artefacts in arc generation.
last read linenumber: 93755
layers: 247
/Users/andrearossetti/Library/Application Support/PrusaSlicer-alpha/prusa_slicer_post_processing_script.py:492: Layer 0: no height found, using layerheight default!
write to file
Code executed successful
Push enter to close this window`

### PR DESCRIPTION
**Pull request by rox97**
Deleting the line to close the program and letting it close itself automatically, i fixed the EOF error that occurred in PrusaSlicer on MacOS. Fix #11 issue
Some other instructions to use white spaces in paths both on unix like systems and windows

### CODE REVIEW

**Review by nicolai-wachenschwan — COMMENTED** [review]
Hey, Thank you for researching this problem! 
Instead of deleting the Input, can you check if assigning a variable like a=input(…
And Next line „pass“ also fixes the problem?
I like the end-input to read through the program  printout…

**Comment by rox97** [comment]
I tried what you suggested me but didn't works, so what do you think about this solution? I updated the README.md whit some new instruction to use on unix like systems to skip the user input, but if you use the script in terminal without the flag -y, you can always use the end-input

**Review by nicolai-wachenschwan — APPROVED** [review]
Love it! You did great work in figuring that out, implementing it and making the documentation better. I have a new job, and I am happy people like you continue improving the Code 😊

**Comment by rox97** [comment]
I'm really happy you liked my solution! Thank you for your work and your great tool!

**Comment by nicolai-wachenschwan** [comment]
Could I ask you for a favour? I googled a bit and found an automatic os detection:
import platform
platform.system()
'Windows' # for Linux it prints 'Linux',
# Mac it prints `'Darwin'

This would reduce the User error to forget the -y flag. 
Do you have time to implement this ?

**Comment by rox97** [comment]
I could give it a try, but in this way every macOS user would skip the user input in the end. the problem is that I can't detect if I'm using the script in PrusaSlicer on macOS or in terminal to skip the end-input only when I use it in the slicer

**Comment by nicolai-wachenschwan** [comment]
Yes, but the input is only needed when used as pp-Script to keep the Window Open.  In concole mode this is automaticly happening. 
On mac this debugging feature wont be accessilbe either way

**Comment by rox97** [comment]
Perfect. I don't have access to a windows terminal so I didn't know how the script ran on it. Please check the new pull request #13  and if you like the new solution, merge. Thank you!

**Pull request merged**
