### PR TITLE
New solution for macOS detecting system

### PR DESCRIPTION
**Pull request by rox97**
This is the new implementation. Give it a look. Feel free to reject the pull request if you don't like the fact that in macOS you will always skip the user input
Referring to  #12

### CODE REVIEW

**Comment by rox97** [comment]
Honestly, I like this solution much more than the old one

**Review by nicolai-wachenschwan — APPROVED** [review]
Thank you, will test it on windows :)

**Comment by nicolai-wachenschwan** [comment]
Test succesful, thank you for implementing and updating the docs!
Like the colaboration where we advance the project, even though we have different systems :)

**Comment by rox97** [comment]
I'm glad everything works fine! I enjoyed our collaboration too. Thank you for your work, keep going!

**Pull request merged**
