### PR TITLE
added Z-height to output on overhangs and a timelapse-option

### PR DESCRIPTION
**Pull request by maruhe**
added Z-height to output on overhangs
also the parameter TimeLapseEveryNArcs was added to create a timelapse-picture every N arcs
if there is no special reason agains it could be great to pass all parameters to arc2GCode-method so adding a parameter to change timelapse-command or adding other parameters could be more easy

### CODE REVIEW

**Comment by maruhe** [comment]
I never created a PullRequest as I liked - will check the docs again..
second commit fixes 2 missing line breaks

**Review by nicolai-wachenschwan — CHANGES_REQUESTED** [review]
Hey, thanks for your corrections!
We can include this feature, but I would prefer it in the main method as 
n=parameters.get("TimeLapseEveryNArcs")
if n!=0 and not ida%n: arcgcode.append("M240\n")

Easier and more readable, but I dont know, how to modify your request :)

**Comment by maruhe** [comment]
I think you'd have to merge the commits and then change the code as you like
or you just delete the request and change the code ;-)

**Comment by nicolai-wachenschwan** [comment]
Took a while, but I integrated the feature. Can you test it on your machine?

**Pull request closed without merging**
